(require 'typescript-mode)
(require 'lsp)

(add-to-list 'auto-mode-alist '("\\.tsx$" . typescript-mode))
(add-to-list 'auto-mode-alist '("\\.jsx$" . typescript-mode))

(defun lunaryorn-use-js-executables-from-node-modules ()
  "Set executables of JS checkers from local node modules."
  (-when-let* ((file-name (buffer-file-name))
               (root (locate-dominating-file file-name "node_modules"))
               (module-directory (expand-file-name "node_modules" root)))
    (pcase-dolist (`(,checker . ,module) '((javascript-jshint . "jshint")
                                           (javascript-eslint . "eslint")
                                           (javascript-jscs   . "jscs")))
      (let ((package-directory (expand-file-name module module-directory))
            (executable-var (flycheck-checker-executable-variable checker)))
        (when (file-directory-p package-directory)
          (set (make-local-variable executable-var)
               (expand-file-name (concat "bin/" module ".js")
                                 package-directory)))))))

(defun mode-config ()
  (setq typescript-indent-level 2))

(defun lsp-config ()
  (setq-local lsp-ui-doc-show-with-cursor t)
  (setq-local lsp-ui-sideline-enable nil))

(add-hook 'typescript-mode-hook (lambda ()
                                  (mode-config)
                                  (lsp-config)
                                  (lsp)
                                  (yas-minor-mode)
                                  (prettier-js-mode)
                                  (add-node-modules-path)
                                  (lunaryorn-use-js-executables-from-node-modules)))
